# Generated by Django 5.2.13 on 2026-06-03 14:58

import django.db.models.deletion
import django_tenants.postgresql_backend.base
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='tenants_only_one_default_shard')],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=120, unique=True)),
                ('status', models.CharField(choices=[('new', 'New (not yet migrated)'), ('pending', 'Pending migration'), ('active', 'Active'), ('deactivated', 'Deactivated'), ('failed', 'Failed')], default='new', max_length=16)),
                ('previous_status', models.CharField(choices=[('new', 'New (not yet migrated)'), ('pending', 'Pending migration'), ('active', 'Active'), ('deactivated', 'Deactivated'), ('failed', 'Failed')], default='new', max_length=16)),
                ('status_changed_at', models.DateTimeField(auto_now=True)),
                ('last_error', models.TextField(blank=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('shard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.shard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
