# Generated by Django 5.2.13 on 2026-09-11 14:44

import django.db.models.deletion
import django.db.models.functions.text
import django.utils.timezone
import django_tenants.postgresql_backend.base
import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedHostRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_type', models.CharField(choices=[('exact', 'Exact host'), ('suffix', 'Domain suffix (host and all subdomains)'), ('label', 'Subdomain label')], max_length=16)),
                ('value', models.CharField(max_length=253)),
                ('base_domain', models.CharField(blank=True, max_length=253)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['match_type', 'value'],
                'constraints': [models.UniqueConstraint(fields=('match_type', 'value', 'base_domain'), name='tenants_reservedhostrule_unique')],
            },
        ),
        migrations.CreateModel(
            name='Shard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='tenants_only_one_default_shard')],
            },
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(max_length=63)),
                ('task', models.CharField(max_length=255)),
                ('args_sig', models.CharField(blank=True, default='', max_length=12)),
                ('last_run_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['task'], name='tenants_taskrun_task_idx')],
                'constraints': [models.UniqueConstraint(fields=('schema', 'task', 'args_sig'), name='tenants_taskrun_unique')],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('company_name', models.CharField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'New (not yet migrated)'), ('pending', 'Pending migration'), ('active', 'Active'), ('deactivated', 'Deactivated'), ('failed', 'Failed')], default='new', max_length=16)),
                ('previous_status', models.CharField(choices=[('new', 'New (not yet migrated)'), ('pending', 'Pending migration'), ('active', 'Active'), ('deactivated', 'Deactivated'), ('failed', 'Failed')], default='new', max_length=16)),
                ('status_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_error', models.TextField(blank=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('timezone', models.CharField(blank=True, default=None, max_length=64, null=True, validators=[tenants.models._validate_timezone])),
                ('shard', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tenants', to='tenants.shard')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('domain', models.Func(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('domain')), models.Value('.'), function='RTRIM'))), name='tenants_domain_canonical')],
            },
        ),
    ]
