# Generated by Django 5.2.13 on 2026-06-09 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shard',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shard',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
