# Generated by Django 5.2.13 on 2026-08-28 13:25

import tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_tenant_company_name_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, validators=[tenants.models._validate_timezone]),
        ),
        migrations.CreateModel(
            name='TaskRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.CharField(max_length=63)),
                ('task', models.CharField(max_length=255)),
                ('last_run_at', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['task'], name='tenants_taskrun_task_idx')],
                'constraints': [models.UniqueConstraint(fields=('schema', 'task'), name='tenants_taskrun_unique')],
            },
        ),
    ]
