# Generated by Django 5.2.13 on 2026-09-03 13:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_tenant_timezone_taskrun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
